### ISSUE TITLE
folder or prefix per message

### ISSUE THREAD

**Issue by pintman** [jamesridgway/attachment-downloader#1]
Currently attachments with the same name in different mails will be overridden. Is it possible to have an option that prefixes the attachments with a Message ID (e.b.) or to put them in a separate folder?

**Comment by jamesridgway** [comment]
It's a very good idea!

In the original problem I was trying to solve all attachments had a unique filename, but I think it will be quite easy to allow the user to customise the format of the attachment name.

I'll look into it for you.

**Comment by jamesridgway** [comment]
Under pull request #2 I have added an ability to specify a filename template.

Using:
- Message ID
- Attachment Name
- Subject
- Local Date

You will be able to specify the structure of the filename used within the download folder.

For example:

    --filename-template="{{local_date}}/{{ message_id }}/{{ subject }}/{{ attachment_name }}"

Will structure attachment downloads in a folder based on date, then message id and finally subject.

I've done it like this because I think that this will allow people to customise the filename structure for their individual use case.

Do you think this will help you? If so I can get this merged and released.

Thanks,
James

**Comment by pintman** [comment]
The format looks promising. Thank you. :)

**Comment by jamesridgway** [comment]
Version 1.1.1 has now been released with this new functionality.

Please feel free to raise any new issues.

Thanks
