### ISSUE TITLE
Possibility to download between datetime

### ISSUE THREAD

**Issue by tristandostaler** [jamesridgway/attachment-downloader#3]
It could be usefull to limit the search of the imap lib search function.
It is probably possible and I found this; I am not sure it helps:
https://stackoverflow.com/questions/2177306/imap-search-limit-the-number-of-messages-returned

I am thinking something like attachment-downloader --BEFORE 2018-01-01-17:30:30 --AFTER 2017-06-06-17:30:30 (or something similar).

**Comment by jamesridgway** [comment]
Feel free to raise a pull request to add the functionality

**Comment by namanjoshi01** [comment]
@tristandostaler just came across here to find a solution to download email attachments, but as you mention I too have same requirement to download attachment for specific criteria:

Like I want to narrow down the timeframe to run this code daily in a much more efficient manner 
1. --> DATE&TIME  FROM & DATE&TIME TO

2. --> I want regex support in the subject title so that only the required email's subject can be download 

Hi @jamesridgway could pls comment if this possible from this library? 
thanks in advance 👍

**Comment by jamesridgway** [comment]
New options have been added in 1.1.3:

```
  --subject-regex=SUBJECT_REGEX
                        Regex that the subject must match against
  --date-after=DATE_AFTER
                        Select messages after this date
  --date-before=DATE_BEFORE
                        Select messages before this date
```

Date filtering can be performed by specifying one or both of the date arguments:

    --date-after="2021-02-06T13:00:00" --date-before="2021-02-06T13:25:00"

Dates should be provided in ISO format, e.g: `2021-02-06T13:25:00` or `2021-02-06T13:25:00`.

If a zone offset is not provided UTC will be assumed.
